"""empty message

Revision ID: 976a0648e0e9
Revises: 5fb6af3e3fc2
Create Date: 2020-03-15 22:47:40.217361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a0648e0e9'
down_revision = '5fb6af3e3fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('dislike_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_count')
    op.drop_column('post', 'dislike_count')
    # ### end Alembic commands ###
