"""empty message

Revision ID: 1ddf5afe3f72
Revises: 2a97fdc521d5
Create Date: 2020-03-21 19:59:44.476560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddf5afe3f72'
down_revision = '2a97fdc521d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_post_id_fk', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.drop_constraint('post_tags_tag_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_tag_id_fkey', 'post_tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_id_fk', 'comment', 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
