"""empty message

Revision ID: 2a97fdc521d5
Revises: eb5bd2cc82cb
Create Date: 2020-03-15 23:11:14.390103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a97fdc521d5'
down_revision = 'eb5bd2cc82cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'dislike_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'dislike_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
